Require search API filtersJson parameter to be non-null
Add a @NotNull annotation to the API method Search.search()'s
filtersJson parameter.

Why? In Swagger UI v3, if you leave filtersJson blank and click the
"Execute" button, no Content-Type header is set, and no body is sent,
and you get an exception leaked out through Tomcat:

javax.servlet.ServletException: java.lang.IllegalStateException: The @FormParam is utilized when the content type of the request entity is not application/x-www-form-urlencoded
        org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:487)
        org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
        org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
        org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
        org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
        org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:198)
        net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:176)
        au.org.ands.vocabs.registry.api.context.ApiOriginFilter.doFilter(ApiOriginFilter.java:77)
root cause java.lang.IllegalStateException: The @FormParam is utilized when the content type of the request entity is not application/x-www-form-urlencoded
        org.glassfish.jersey.server.internal.inject.FormParamValueFactoryProvider$FormParamValueFactory.ensureValidRequest(FormParamValueFactoryProvider.java:183)
        org.glassfish.jersey.server.internal.inject.FormParamValueFactoryProvider$FormParamValueFactory.getForm(FormParamValueFactoryProvider.java:167)
        org.glassfish.jersey.server.internal.inject.FormParamValueFactoryProvider$FormParamValueFactory.provide(FormParamValueFactoryProvider.java:118)
        org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.provide(ParamValueFactoryWithSource.java:71)
        org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:90)
        org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127)
        org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
        org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
        org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
        org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
        org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
        org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:198)
        net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:176)
        au.org.ands.vocabs.registry.api.context.ApiOriginFilter.doFilter(ApiOriginFilter.java:77)

This commit doesn't change what happens if no Content-Type header and
no body is sent, but it does stop users of the Swagger UI from
clicking the Execute button if the parameter is blank!